// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5h3QhDqWM84XV2vDpdccG7
// Component: lwJE8KUYjX
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Back from "../../Back"; // plasmic-import: 2dYzKl3MFK/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_x_manage_project.module.css"; // plasmic-import: 5h3QhDqWM84XV2vDpdccG7/projectcss
import sty from "./PlasmicProjectsdetails.module.css"; // plasmic-import: lwJE8KUYjX/css
import Rectangle7Icon from "./icons/PlasmicIcon__Rectangle7"; // plasmic-import: mM3LZX6jH7O/icon
import rectangle24Yu3W3K3MNj from "./images/rectangle24.svg"; // plasmic-import: YU3w3k3mNj/picture

export const PlasmicProjectsdetails__VariantProps = new Array();

export const PlasmicProjectsdetails__ArgProps = new Array();

function PlasmicProjectsdetails__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"desktop6"}
            data-plasmic-override={overrides.desktop6}
            className={classNames(projectcss.all, sty.desktop6)}
          >
            <Rectangle7Icon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg)}
              role={"img"}
            />

            <div
              data-plasmic-name={"rectangle15"}
              data-plasmic-override={overrides.rectangle15}
              className={classNames(projectcss.all, sty.rectangle15)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___9Lb5O
              )}
            >
              {"Username"}
            </div>

            <a
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__xzTc6
              )}
              href={`/expensespage`}
            >
              {"Expenses"}
            </a>

            <a
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__rH5E4
              )}
            >
              {"Dashboard"}
            </a>

            <a
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__lMqB2
              )}
              href={`/projectspage`}
            >
              {"Projects"}
            </a>

            <a
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__fTA8
              )}
              href={`/toolspage`}
            >
              {"Tools"}
            </a>

            <div
              data-plasmic-name={"fullToolStorageBox"}
              data-plasmic-override={overrides.fullToolStorageBox}
              className={classNames(projectcss.all, sty.fullToolStorageBox)}
            />

            <div
              data-plasmic-name={"project"}
              data-plasmic-override={overrides.project}
              className={classNames(projectcss.all, sty.project)}
            />

            <div
              data-plasmic-name={"cost"}
              data-plasmic-override={overrides.cost}
              className={classNames(projectcss.all, sty.cost)}
            />

            <div
              data-plasmic-name={"speed"}
              data-plasmic-override={overrides.speed}
              className={classNames(projectcss.all, sty.speed)}
            />

            <div
              data-plasmic-name={"user"}
              data-plasmic-override={overrides.user}
              className={classNames(projectcss.all, sty.user)}
            />

            <div
              data-plasmic-name={"rectangle23"}
              data-plasmic-override={overrides.rectangle23}
              className={classNames(projectcss.all, sty.rectangle23)}
            />

            <div
              data-plasmic-name={"search"}
              data-plasmic-override={overrides.search}
              className={classNames(projectcss.all, sty.search)}
            />

            <p.PlasmicImg
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"44px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"321px"}
              loading={"lazy"}
              src={{
                src: rectangle24Yu3W3K3MNj,
                fullWidth: 321,
                fullHeight: 44,
                aspectRatio: 7.295455
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__feisx
              )}
            >
              {"Search"}
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame70"}
              data-plasmic-override={overrides.frame70}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame70)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5HjV1
                )}
              >
                {"Project ID"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame85"}
              data-plasmic-override={overrides.frame85}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame85)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tw7X
                )}
              >
                {"P001-22"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame99"}
              data-plasmic-override={overrides.frame99}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame99)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__b5YuX
                )}
              >
                {"5"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame101"}
              data-plasmic-override={overrides.frame101}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame101)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cPgDt
                )}
              >
                {"Ongoing"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame98"}
              data-plasmic-override={overrides.frame98}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame98)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aUfnV
                )}
              >
                {"30"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame97"}
              data-plasmic-override={overrides.frame97}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame97)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___7PJmy
                )}
              >
                {"Zineb"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame96"}
              data-plasmic-override={overrides.frame96}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame96)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pTOl
                )}
              >
                {"56 JOURS"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame95"}
              data-plasmic-override={overrides.frame95}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame95)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uPmVc
                )}
              >
                {"30/07/22"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame94"}
              data-plasmic-override={overrides.frame94}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame94)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dNtNl
                )}
              >
                {"ABO BUSINESS"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame93"}
              data-plasmic-override={overrides.frame93}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame93)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eMrn
                )}
              >
                {"475000"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame92"}
              data-plasmic-override={overrides.frame92}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame92)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wh3Rz
                )}
              >
                {"500000"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame91"}
              data-plasmic-override={overrides.frame91}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame91)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__o4Rp6
                )}
              >
                {"30/07/22"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame90"}
              data-plasmic-override={overrides.frame90}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame90)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yJqa
                )}
              >
                {"Project ID"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame89"}
              data-plasmic-override={overrides.frame89}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame89)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1Xftx
                )}
              >
                {"+227986780036"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame88"}
              data-plasmic-override={overrides.frame88}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame88)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qNafp
                )}
              >
                {"aboumarrou17@gmail.com"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame87"}
              data-plasmic-override={overrides.frame87}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame87)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tH7Gi
                )}
              >
                {"Adama Boubacar Oumarou"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame86"}
              data-plasmic-override={overrides.frame86}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame86)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pi4FE
                )}
              >
                {"Projet de cartographie Temara"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame84"}
              data-plasmic-override={overrides.frame84}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame84)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jSi2
                )}
              >
                {"Used tools"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame100"}
              data-plasmic-override={overrides.frame100}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame100)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wfj3
                )}
              >
                {"Status"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame83"}
              data-plasmic-override={overrides.frame83}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame83)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__foE6T
                )}
              >
                {"Expenses"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame82"}
              data-plasmic-override={overrides.frame82}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame82)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gqTtk
                )}
              >
                {"Responsible"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame81"}
              data-plasmic-override={overrides.frame81}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame81)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jgBp
                )}
              >
                {"Duration"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame80"}
              data-plasmic-override={overrides.frame80}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame80)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___50PXi
                )}
              >
                {"Starting date"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame79"}
              data-plasmic-override={overrides.frame79}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame79)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2Ucjo
                )}
              >
                {"Company name"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame78"}
              data-plasmic-override={overrides.frame78}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame78)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__g0Ty0
                )}
              >
                {"Estimated amount"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame77"}
              data-plasmic-override={overrides.frame77}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame77)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bgnYg
                )}
              >
                {"Amount"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame76"}
              data-plasmic-override={overrides.frame76}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame76)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hxiJo
                )}
              >
                {"Acquisition Date"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame75"}
              data-plasmic-override={overrides.frame75}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame75)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__do4Ri
                )}
              >
                {"Business ID"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame74"}
              data-plasmic-override={overrides.frame74}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame74)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3F3C0
                )}
              >
                {"Client Phone"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame73"}
              data-plasmic-override={overrides.frame73}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame73)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__do717
                )}
              >
                {"Client Email"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame72"}
              data-plasmic-override={overrides.frame72}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame72)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rotD
                )}
              >
                {"Client Name"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame71"}
              data-plasmic-override={overrides.frame71}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame71)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___29BxC
                )}
              >
                {"Project Name"}
              </div>
            </p.Stack>

            <a
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.link__uXSu
              )}
            >
              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__pt2V3
                )}
              >
                <a
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link___91D8L
                  )}
                >
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__s9PQj
                    )}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__gze35
                      )}
                    >
                      <Back
                        data-plasmic-name={"back"}
                        data-plasmic-override={overrides.back}
                        className={classNames("__wab_instance", sty.back)}
                      />
                    </a>
                  </a>
                </a>
              </a>
            </a>

            <div
              data-plasmic-name={"rectangle65"}
              data-plasmic-override={overrides.rectangle65}
              className={classNames(projectcss.all, sty.rectangle65)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__d3Bx0
              )}
            >
              {"Company Logo"}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "desktop6",
    "svg",
    "rectangle15",
    "fullToolStorageBox",
    "project",
    "cost",
    "speed",
    "user",
    "rectangle23",
    "search",
    "img",
    "frame70",
    "frame85",
    "frame99",
    "frame101",
    "frame98",
    "frame97",
    "frame96",
    "frame95",
    "frame94",
    "frame93",
    "frame92",
    "frame91",
    "frame90",
    "frame89",
    "frame88",
    "frame87",
    "frame86",
    "frame84",
    "frame100",
    "frame83",
    "frame82",
    "frame81",
    "frame80",
    "frame79",
    "frame78",
    "frame77",
    "frame76",
    "frame75",
    "frame74",
    "frame73",
    "frame72",
    "frame71",
    "back",
    "rectangle65"
  ],

  desktop6: [
    "desktop6",
    "svg",
    "rectangle15",
    "fullToolStorageBox",
    "project",
    "cost",
    "speed",
    "user",
    "rectangle23",
    "search",
    "img",
    "frame70",
    "frame85",
    "frame99",
    "frame101",
    "frame98",
    "frame97",
    "frame96",
    "frame95",
    "frame94",
    "frame93",
    "frame92",
    "frame91",
    "frame90",
    "frame89",
    "frame88",
    "frame87",
    "frame86",
    "frame84",
    "frame100",
    "frame83",
    "frame82",
    "frame81",
    "frame80",
    "frame79",
    "frame78",
    "frame77",
    "frame76",
    "frame75",
    "frame74",
    "frame73",
    "frame72",
    "frame71",
    "back",
    "rectangle65"
  ],

  svg: ["svg"],
  rectangle15: ["rectangle15"],
  fullToolStorageBox: ["fullToolStorageBox"],
  project: ["project"],
  cost: ["cost"],
  speed: ["speed"],
  user: ["user"],
  rectangle23: ["rectangle23"],
  search: ["search"],
  img: ["img"],
  frame70: ["frame70"],
  frame85: ["frame85"],
  frame99: ["frame99"],
  frame101: ["frame101"],
  frame98: ["frame98"],
  frame97: ["frame97"],
  frame96: ["frame96"],
  frame95: ["frame95"],
  frame94: ["frame94"],
  frame93: ["frame93"],
  frame92: ["frame92"],
  frame91: ["frame91"],
  frame90: ["frame90"],
  frame89: ["frame89"],
  frame88: ["frame88"],
  frame87: ["frame87"],
  frame86: ["frame86"],
  frame84: ["frame84"],
  frame100: ["frame100"],
  frame83: ["frame83"],
  frame82: ["frame82"],
  frame81: ["frame81"],
  frame80: ["frame80"],
  frame79: ["frame79"],
  frame78: ["frame78"],
  frame77: ["frame77"],
  frame76: ["frame76"],
  frame75: ["frame75"],
  frame74: ["frame74"],
  frame73: ["frame73"],
  frame72: ["frame72"],
  frame71: ["frame71"],
  back: ["back"],
  rectangle65: ["rectangle65"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicProjectsdetails__ArgProps,
          internalVariantPropNames: PlasmicProjectsdetails__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicProjectsdetails__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProjectsdetails";
  } else {
    func.displayName = `PlasmicProjectsdetails.${nodeName}`;
  }
  return func;
}

export const PlasmicProjectsdetails = Object.assign(
  // Top-level PlasmicProjectsdetails renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    desktop6: makeNodeComponent("desktop6"),
    svg: makeNodeComponent("svg"),
    rectangle15: makeNodeComponent("rectangle15"),
    fullToolStorageBox: makeNodeComponent("fullToolStorageBox"),
    project: makeNodeComponent("project"),
    cost: makeNodeComponent("cost"),
    speed: makeNodeComponent("speed"),
    user: makeNodeComponent("user"),
    rectangle23: makeNodeComponent("rectangle23"),
    search: makeNodeComponent("search"),
    img: makeNodeComponent("img"),
    frame70: makeNodeComponent("frame70"),
    frame85: makeNodeComponent("frame85"),
    frame99: makeNodeComponent("frame99"),
    frame101: makeNodeComponent("frame101"),
    frame98: makeNodeComponent("frame98"),
    frame97: makeNodeComponent("frame97"),
    frame96: makeNodeComponent("frame96"),
    frame95: makeNodeComponent("frame95"),
    frame94: makeNodeComponent("frame94"),
    frame93: makeNodeComponent("frame93"),
    frame92: makeNodeComponent("frame92"),
    frame91: makeNodeComponent("frame91"),
    frame90: makeNodeComponent("frame90"),
    frame89: makeNodeComponent("frame89"),
    frame88: makeNodeComponent("frame88"),
    frame87: makeNodeComponent("frame87"),
    frame86: makeNodeComponent("frame86"),
    frame84: makeNodeComponent("frame84"),
    frame100: makeNodeComponent("frame100"),
    frame83: makeNodeComponent("frame83"),
    frame82: makeNodeComponent("frame82"),
    frame81: makeNodeComponent("frame81"),
    frame80: makeNodeComponent("frame80"),
    frame79: makeNodeComponent("frame79"),
    frame78: makeNodeComponent("frame78"),
    frame77: makeNodeComponent("frame77"),
    frame76: makeNodeComponent("frame76"),
    frame75: makeNodeComponent("frame75"),
    frame74: makeNodeComponent("frame74"),
    frame73: makeNodeComponent("frame73"),
    frame72: makeNodeComponent("frame72"),
    frame71: makeNodeComponent("frame71"),
    back: makeNodeComponent("back"),
    rectangle65: makeNodeComponent("rectangle65"),
    // Metadata about props expected for PlasmicProjectsdetails
    internalVariantProps: PlasmicProjectsdetails__VariantProps,
    internalArgProps: PlasmicProjectsdetails__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicProjectsdetails;
/* prettier-ignore-end */
