// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5h3QhDqWM84XV2vDpdccG7
// Component: fJw77-BYn8
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_x_manage_project.module.css"; // plasmic-import: 5h3QhDqWM84XV2vDpdccG7/projectcss
import sty from "./PlasmicProjectspage.module.css"; // plasmic-import: fJw77-BYn8/css
import Rectangle7Icon from "./icons/PlasmicIcon__Rectangle7"; // plasmic-import: mM3LZX6jH7O/icon
import Rectangle28Icon from "./icons/PlasmicIcon__Rectangle28"; // plasmic-import: GDn1fNQ59Z/icon
import Arrow1Icon from "./icons/PlasmicIcon__Arrow1"; // plasmic-import: bei6iQA9x/icon

export const PlasmicProjectspage__VariantProps = new Array();

export const PlasmicProjectspage__ArgProps = new Array();

function PlasmicProjectspage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"desktop4"}
            data-plasmic-override={overrides.desktop4}
            className={classNames(projectcss.all, sty.desktop4)}
          >
            <Rectangle7Icon
              className={classNames(projectcss.all, sty.svg__iPve)}
              role={"img"}
            />

            <div
              data-plasmic-name={"rectangle15"}
              data-plasmic-override={overrides.rectangle15}
              className={classNames(projectcss.all, sty.rectangle15)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ir55U
              )}
            >
              {"Username"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__dpVr
              )}
            >
              {"Expenses"}
            </div>

            <a
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link__i2S4
              )}
            >
              {"Dashboard"}
            </a>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___5AHo2
              )}
            >
              {"Projects"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ksxA9
              )}
            >
              {"Tools"}
            </div>

            <div
              data-plasmic-name={"fullToolStorageBox"}
              data-plasmic-override={overrides.fullToolStorageBox}
              className={classNames(projectcss.all, sty.fullToolStorageBox)}
            />

            <div
              data-plasmic-name={"project"}
              data-plasmic-override={overrides.project}
              className={classNames(projectcss.all, sty.project)}
            />

            <div
              data-plasmic-name={"cost"}
              data-plasmic-override={overrides.cost}
              className={classNames(projectcss.all, sty.cost)}
            />

            <div
              data-plasmic-name={"speed"}
              data-plasmic-override={overrides.speed}
              className={classNames(projectcss.all, sty.speed)}
            />

            <div
              data-plasmic-name={"user"}
              data-plasmic-override={overrides.user}
              className={classNames(projectcss.all, sty.user)}
            />

            <div
              data-plasmic-name={"projectName"}
              data-plasmic-override={overrides.projectName}
              className={classNames(projectcss.all, sty.projectName)}
            >
              <a
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__xKbvQ
                )}
                href={`/projects`}
              >
                {"Project Name"}
              </a>
            </div>

            <div
              data-plasmic-name={"projectName2"}
              data-plasmic-override={overrides.projectName2}
              className={classNames(projectcss.all, sty.projectName2)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zsfvZ
                )}
              >
                {"Project Name"}
              </div>
            </div>

            <div
              data-plasmic-name={"projectName3"}
              data-plasmic-override={overrides.projectName3}
              className={classNames(projectcss.all, sty.projectName3)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__r3K3
                )}
              >
                {"Project Name"}
              </div>
            </div>

            <div
              data-plasmic-name={"projectName4"}
              data-plasmic-override={overrides.projectName4}
              className={classNames(projectcss.all, sty.projectName4)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ydDnd
                )}
              >
                {"Project Name"}
              </div>
            </div>

            <div
              data-plasmic-name={"rectangle25"}
              data-plasmic-override={overrides.rectangle25}
              className={classNames(projectcss.all, sty.rectangle25)}
            />

            <div
              data-plasmic-name={"rectangle26"}
              data-plasmic-override={overrides.rectangle26}
              className={classNames(projectcss.all, sty.rectangle26)}
            />

            <div
              data-plasmic-name={"rectangle27"}
              data-plasmic-override={overrides.rectangle27}
              className={classNames(projectcss.all, sty.rectangle27)}
            />

            <Rectangle28Icon
              className={classNames(projectcss.all, sty.svg__u3I7)}
              role={"img"}
            />

            <div
              data-plasmic-name={"p00122"}
              data-plasmic-override={overrides.p00122}
              className={classNames(projectcss.all, sty.p00122)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__x6VAt
                )}
              >
                {"P001-22"}
              </div>
            </div>

            <div
              data-plasmic-name={"completed"}
              data-plasmic-override={overrides.completed}
              className={classNames(projectcss.all, sty.completed)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iVSkc
                )}
              >
                {"Completed"}
              </div>
            </div>

            <div
              data-plasmic-name={"onGoing"}
              data-plasmic-override={overrides.onGoing}
              className={classNames(projectcss.all, sty.onGoing)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hVrpe
                )}
              >
                {"On going"}
              </div>
            </div>

            <div
              data-plasmic-name={"started"}
              data-plasmic-override={overrides.started}
              className={classNames(projectcss.all, sty.started)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tWvC
                )}
              >
                {"Started"}
              </div>
            </div>

            <div
              data-plasmic-name={"late"}
              data-plasmic-override={overrides.late}
              className={classNames(projectcss.all, sty.late)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lFlz8
                )}
              >
                {"Late"}
              </div>
            </div>

            <div
              data-plasmic-name={"p001222"}
              data-plasmic-override={overrides.p001222}
              className={classNames(projectcss.all, sty.p001222)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__la7Yv
                )}
              >
                {"P001-22"}
              </div>
            </div>

            <div
              data-plasmic-name={"p001223"}
              data-plasmic-override={overrides.p001223}
              className={classNames(projectcss.all, sty.p001223)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__smcpI
                )}
              >
                {"P001-22"}
              </div>
            </div>

            <div
              data-plasmic-name={"p001224"}
              data-plasmic-override={overrides.p001224}
              className={classNames(projectcss.all, sty.p001224)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__opE4T
                )}
              >
                {"P001-22"}
              </div>
            </div>

            <div
              data-plasmic-name={"lessThan"}
              data-plasmic-override={overrides.lessThan}
              className={classNames(projectcss.all, sty.lessThan)}
            />

            <div
              data-plasmic-name={"moreThan"}
              data-plasmic-override={overrides.moreThan}
              className={classNames(projectcss.all, sty.moreThan)}
            />

            <div
              data-plasmic-name={"rectangle23"}
              data-plasmic-override={overrides.rectangle23}
              className={classNames(projectcss.all, sty.rectangle23)}
            />

            <div
              data-plasmic-name={"search"}
              data-plasmic-override={overrides.search}
              className={classNames(projectcss.all, sty.search)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mGUqY
              )}
            >
              {"Chercher"}
            </div>

            <div
              data-plasmic-name={"rectangle24"}
              data-plasmic-override={overrides.rectangle24}
              className={classNames(projectcss.all, sty.rectangle24)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rVeCd
              )}
            >
              {"Chercher"}
            </div>

            <div
              data-plasmic-name={"search2"}
              data-plasmic-override={overrides.search2}
              className={classNames(projectcss.all, sty.search2)}
            />

            <div
              data-plasmic-name={"rectangle29"}
              data-plasmic-override={overrides.rectangle29}
              className={classNames(projectcss.all, sty.rectangle29)}
            />

            <div
              data-plasmic-name={"search3"}
              data-plasmic-override={overrides.search3}
              className={classNames(projectcss.all, sty.search3)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__r8Uo7
              )}
            >
              {"Chercher"}
            </div>

            <div
              data-plasmic-name={"rectangle30"}
              data-plasmic-override={overrides.rectangle30}
              className={classNames(projectcss.all, sty.rectangle30)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__gs99
              )}
            >
              {"Search"}
            </div>

            <div
              data-plasmic-name={"search4"}
              data-plasmic-override={overrides.search4}
              className={classNames(projectcss.all, sty.search4)}
            />

            <Arrow1Icon
              className={classNames(projectcss.all, sty.svg___1HjYg)}
              role={"img"}
            />

            <div
              data-plasmic-name={"desktop5"}
              data-plasmic-override={overrides.desktop5}
              className={classNames(projectcss.all, sty.desktop5)}
            >
              <Rectangle7Icon
                className={classNames(projectcss.all, sty.svg__lmLm3)}
                role={"img"}
              />

              <div
                data-plasmic-name={"rectangle16"}
                data-plasmic-override={overrides.rectangle16}
                className={classNames(projectcss.all, sty.rectangle16)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mBXng
                )}
              >
                {"Nom Utilisateurs"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3Rx1F
                )}
              >
                {"Dépenses"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___7Rusq
                )}
              >
                {"Acceuil"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___84Oee
                )}
              >
                {"Projets"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iKMl
                )}
              >
                {"Matériels"}
              </div>

              <div
                data-plasmic-name={"fullToolStorageBox2"}
                data-plasmic-override={overrides.fullToolStorageBox2}
                className={classNames(projectcss.all, sty.fullToolStorageBox2)}
              />

              <div
                data-plasmic-name={"project2"}
                data-plasmic-override={overrides.project2}
                className={classNames(projectcss.all, sty.project2)}
              />

              <div
                data-plasmic-name={"cost2"}
                data-plasmic-override={overrides.cost2}
                className={classNames(projectcss.all, sty.cost2)}
              />

              <div
                data-plasmic-name={"speed2"}
                data-plasmic-override={overrides.speed2}
                className={classNames(projectcss.all, sty.speed2)}
              />

              <div
                data-plasmic-name={"user2"}
                data-plasmic-override={overrides.user2}
                className={classNames(projectcss.all, sty.user2)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pi5X
                )}
              >
                {"Déconexion"}
              </div>

              <div
                data-plasmic-name={"logout"}
                data-plasmic-override={overrides.logout}
                className={classNames(projectcss.all, sty.logout)}
              />

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame36"}
                data-plasmic-override={overrides.frame36}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame36)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ai4D9
                  )}
                >
                  {"Matériel ID"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame39"}
                data-plasmic-override={overrides.frame39}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame39)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__u5WrB
                  )}
                >
                  {"Tool ID"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame38"}
                data-plasmic-override={overrides.frame38}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame38)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kyr7Y
                  )}
                >
                  {"Tool ID"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame37"}
                data-plasmic-override={overrides.frame37}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame37)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xeKx0
                  )}
                >
                  {"M-001"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame40"}
                data-plasmic-override={overrides.frame40}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame40)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__f37F
                  )}
                >
                  {"K-002"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame65"}
                data-plasmic-override={overrides.frame65}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame65)}
              >
                <div
                  data-plasmic-name={"responsable"}
                  data-plasmic-override={overrides.responsable}
                  className={classNames(projectcss.all, sty.responsable)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__s0D72
                    )}
                  >
                    {"Responsable"}
                  </div>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame66"}
                data-plasmic-override={overrides.frame66}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame66)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kCUjU
                  )}
                >
                  {"Admin"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame67"}
                data-plasmic-override={overrides.frame67}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame67)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5ElNv
                  )}
                >
                  {"Zinab"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame68"}
                data-plasmic-override={overrides.frame68}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame68)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5UuK6
                  )}
                >
                  {"Adama"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame69"}
                data-plasmic-override={overrides.frame69}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame69)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__r3S7Y
                  )}
                >
                  {"Admin"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame55"}
                data-plasmic-override={overrides.frame55}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame55)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__irqgy
                  )}
                >
                  {"Disponibilité"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame56"}
                data-plasmic-override={overrides.frame56}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame56)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pC5Xj
                  )}
                >
                  {"30/07/22"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame57"}
                data-plasmic-override={overrides.frame57}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame57)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gHcgb
                  )}
                >
                  {"30/07/22"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame58"}
                data-plasmic-override={overrides.frame58}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame58)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__odDla
                  )}
                >
                  {"30/07/22"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame59"}
                data-plasmic-override={overrides.frame59}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame59)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bqy01
                  )}
                >
                  {"30/07/22"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame50"}
                data-plasmic-override={overrides.frame50}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame50)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gW5NM
                  )}
                >
                  {"Durée"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame51"}
                data-plasmic-override={overrides.frame51}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame51)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uw8De
                  )}
                >
                  {"4"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame52"}
                data-plasmic-override={overrides.frame52}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame52)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vYgwk
                  )}
                >
                  {"1"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame53"}
                data-plasmic-override={overrides.frame53}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame53)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___01SnX
                  )}
                >
                  {"2"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame54"}
                data-plasmic-override={overrides.frame54}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame54)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__agnSb
                  )}
                >
                  {"0"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame45"}
                data-plasmic-override={overrides.frame45}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame45)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yjdys
                  )}
                >
                  {"Type"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame46"}
                data-plasmic-override={overrides.frame46}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame46)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pc1GN
                  )}
                >
                  {"Tool ID"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame47"}
                data-plasmic-override={overrides.frame47}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame47)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jImd
                  )}
                >
                  {"Tool ID"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame48"}
                data-plasmic-override={overrides.frame48}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame48)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lic8
                  )}
                >
                  {"Véhicule"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame49"}
                data-plasmic-override={overrides.frame49}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame49)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mZZwd
                  )}
                >
                  {"Ordinanteur"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame60"}
                data-plasmic-override={overrides.frame60}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame60)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rPcO5
                  )}
                >
                  {"Statut"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame61"}
                data-plasmic-override={overrides.frame61}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame61)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ha1Zq
                  )}
                >
                  {"Tool ID"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame62"}
                data-plasmic-override={overrides.frame62}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame62)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uREmJ
                  )}
                >
                  {"Tool ID"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame63"}
                data-plasmic-override={overrides.frame63}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame63)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3Wpst
                  )}
                >
                  {"reservé"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame64"}
                data-plasmic-override={overrides.frame64}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame64)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lg4Os
                  )}
                >
                  {"disponible"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame41"}
                data-plasmic-override={overrides.frame41}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame41)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sMmIv
                  )}
                >
                  {"Nom"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame42"}
                data-plasmic-override={overrides.frame42}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame42)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rGy3
                  )}
                >
                  {"Tool ID"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame43"}
                data-plasmic-override={overrides.frame43}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame43)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gu75X
                  )}
                >
                  {"Tool ID"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame44"}
                data-plasmic-override={overrides.frame44}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame44)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__stjiH
                  )}
                >
                  {"Toyota"}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame70"}
                data-plasmic-override={overrides.frame70}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame70)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ggjLz
                  )}
                >
                  {"HP 505"}
                </div>
              </p.Stack>

              <div
                data-plasmic-name={"rectangle28"}
                data-plasmic-override={overrides.rectangle28}
                className={classNames(projectcss.all, sty.rectangle28)}
              />

              <div
                data-plasmic-name={"search5"}
                data-plasmic-override={overrides.search5}
                className={classNames(projectcss.all, sty.search5)}
              />

              <div
                data-plasmic-name={"plus"}
                data-plasmic-override={overrides.plus}
                className={classNames(projectcss.all, sty.plus)}
              />

              <div
                data-plasmic-name={"plus2"}
                data-plasmic-override={overrides.plus2}
                className={classNames(projectcss.all, sty.plus2)}
              />

              <div
                data-plasmic-name={"plus3"}
                data-plasmic-override={overrides.plus3}
                className={classNames(projectcss.all, sty.plus3)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__amXbc
                )}
              >
                {"Ajouter  une requête"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eZw5R
                )}
              >
                {"Chercher"}
              </div>

              <div
                data-plasmic-name={"rectangle31"}
                data-plasmic-override={overrides.rectangle31}
                className={classNames(projectcss.all, sty.rectangle31)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8QkIr
                )}
              >
                {"Chercher"}
              </div>

              <div
                data-plasmic-name={"search6"}
                data-plasmic-override={overrides.search6}
                className={classNames(projectcss.all, sty.search6)}
              />

              <div
                data-plasmic-name={"noEntry"}
                data-plasmic-override={overrides.noEntry}
                className={classNames(projectcss.all, sty.noEntry)}
              />

              <div
                data-plasmic-name={"noEntry2"}
                data-plasmic-override={overrides.noEntry2}
                className={classNames(projectcss.all, sty.noEntry2)}
              />

              <Arrow1Icon
                className={classNames(projectcss.all, sty.svg___8OjTd)}
                role={"img"}
              />

              <div
                data-plasmic-name={"cursor2"}
                data-plasmic-override={overrides.cursor2}
                className={classNames(projectcss.all, sty.cursor2)}
              />

              <div
                data-plasmic-name={"xyConceptNbg1"}
                data-plasmic-override={overrides.xyConceptNbg1}
                className={classNames(projectcss.all, sty.xyConceptNbg1)}
              />
            </div>

            <div
              data-plasmic-name={"rectangle65"}
              data-plasmic-override={overrides.rectangle65}
              className={classNames(projectcss.all, sty.rectangle65)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___2Xqz9
              )}
            >
              {"Company Logo"}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "desktop4",
    "rectangle15",
    "fullToolStorageBox",
    "project",
    "cost",
    "speed",
    "user",
    "projectName",
    "projectName2",
    "projectName3",
    "projectName4",
    "rectangle25",
    "rectangle26",
    "rectangle27",
    "p00122",
    "completed",
    "onGoing",
    "started",
    "late",
    "p001222",
    "p001223",
    "p001224",
    "lessThan",
    "moreThan",
    "rectangle23",
    "search",
    "rectangle24",
    "search2",
    "rectangle29",
    "search3",
    "rectangle30",
    "search4",
    "desktop5",
    "rectangle16",
    "fullToolStorageBox2",
    "project2",
    "cost2",
    "speed2",
    "user2",
    "logout",
    "frame36",
    "frame39",
    "frame38",
    "frame37",
    "frame40",
    "frame65",
    "responsable",
    "frame66",
    "frame67",
    "frame68",
    "frame69",
    "frame55",
    "frame56",
    "frame57",
    "frame58",
    "frame59",
    "frame50",
    "frame51",
    "frame52",
    "frame53",
    "frame54",
    "frame45",
    "frame46",
    "frame47",
    "frame48",
    "frame49",
    "frame60",
    "frame61",
    "frame62",
    "frame63",
    "frame64",
    "frame41",
    "frame42",
    "frame43",
    "frame44",
    "frame70",
    "rectangle28",
    "search5",
    "plus",
    "plus2",
    "plus3",
    "rectangle31",
    "search6",
    "noEntry",
    "noEntry2",
    "cursor2",
    "xyConceptNbg1",
    "rectangle65"
  ],

  desktop4: [
    "desktop4",
    "rectangle15",
    "fullToolStorageBox",
    "project",
    "cost",
    "speed",
    "user",
    "projectName",
    "projectName2",
    "projectName3",
    "projectName4",
    "rectangle25",
    "rectangle26",
    "rectangle27",
    "p00122",
    "completed",
    "onGoing",
    "started",
    "late",
    "p001222",
    "p001223",
    "p001224",
    "lessThan",
    "moreThan",
    "rectangle23",
    "search",
    "rectangle24",
    "search2",
    "rectangle29",
    "search3",
    "rectangle30",
    "search4",
    "desktop5",
    "rectangle16",
    "fullToolStorageBox2",
    "project2",
    "cost2",
    "speed2",
    "user2",
    "logout",
    "frame36",
    "frame39",
    "frame38",
    "frame37",
    "frame40",
    "frame65",
    "responsable",
    "frame66",
    "frame67",
    "frame68",
    "frame69",
    "frame55",
    "frame56",
    "frame57",
    "frame58",
    "frame59",
    "frame50",
    "frame51",
    "frame52",
    "frame53",
    "frame54",
    "frame45",
    "frame46",
    "frame47",
    "frame48",
    "frame49",
    "frame60",
    "frame61",
    "frame62",
    "frame63",
    "frame64",
    "frame41",
    "frame42",
    "frame43",
    "frame44",
    "frame70",
    "rectangle28",
    "search5",
    "plus",
    "plus2",
    "plus3",
    "rectangle31",
    "search6",
    "noEntry",
    "noEntry2",
    "cursor2",
    "xyConceptNbg1",
    "rectangle65"
  ],

  rectangle15: ["rectangle15"],
  fullToolStorageBox: ["fullToolStorageBox"],
  project: ["project"],
  cost: ["cost"],
  speed: ["speed"],
  user: ["user"],
  projectName: ["projectName"],
  projectName2: ["projectName2"],
  projectName3: ["projectName3"],
  projectName4: ["projectName4"],
  rectangle25: ["rectangle25"],
  rectangle26: ["rectangle26"],
  rectangle27: ["rectangle27"],
  p00122: ["p00122"],
  completed: ["completed"],
  onGoing: ["onGoing"],
  started: ["started"],
  late: ["late"],
  p001222: ["p001222"],
  p001223: ["p001223"],
  p001224: ["p001224"],
  lessThan: ["lessThan"],
  moreThan: ["moreThan"],
  rectangle23: ["rectangle23"],
  search: ["search"],
  rectangle24: ["rectangle24"],
  search2: ["search2"],
  rectangle29: ["rectangle29"],
  search3: ["search3"],
  rectangle30: ["rectangle30"],
  search4: ["search4"],
  desktop5: [
    "desktop5",
    "rectangle16",
    "fullToolStorageBox2",
    "project2",
    "cost2",
    "speed2",
    "user2",
    "logout",
    "frame36",
    "frame39",
    "frame38",
    "frame37",
    "frame40",
    "frame65",
    "responsable",
    "frame66",
    "frame67",
    "frame68",
    "frame69",
    "frame55",
    "frame56",
    "frame57",
    "frame58",
    "frame59",
    "frame50",
    "frame51",
    "frame52",
    "frame53",
    "frame54",
    "frame45",
    "frame46",
    "frame47",
    "frame48",
    "frame49",
    "frame60",
    "frame61",
    "frame62",
    "frame63",
    "frame64",
    "frame41",
    "frame42",
    "frame43",
    "frame44",
    "frame70",
    "rectangle28",
    "search5",
    "plus",
    "plus2",
    "plus3",
    "rectangle31",
    "search6",
    "noEntry",
    "noEntry2",
    "cursor2",
    "xyConceptNbg1"
  ],

  rectangle16: ["rectangle16"],
  fullToolStorageBox2: ["fullToolStorageBox2"],
  project2: ["project2"],
  cost2: ["cost2"],
  speed2: ["speed2"],
  user2: ["user2"],
  logout: ["logout"],
  frame36: ["frame36"],
  frame39: ["frame39"],
  frame38: ["frame38"],
  frame37: ["frame37"],
  frame40: ["frame40"],
  frame65: ["frame65", "responsable"],
  responsable: ["responsable"],
  frame66: ["frame66"],
  frame67: ["frame67"],
  frame68: ["frame68"],
  frame69: ["frame69"],
  frame55: ["frame55"],
  frame56: ["frame56"],
  frame57: ["frame57"],
  frame58: ["frame58"],
  frame59: ["frame59"],
  frame50: ["frame50"],
  frame51: ["frame51"],
  frame52: ["frame52"],
  frame53: ["frame53"],
  frame54: ["frame54"],
  frame45: ["frame45"],
  frame46: ["frame46"],
  frame47: ["frame47"],
  frame48: ["frame48"],
  frame49: ["frame49"],
  frame60: ["frame60"],
  frame61: ["frame61"],
  frame62: ["frame62"],
  frame63: ["frame63"],
  frame64: ["frame64"],
  frame41: ["frame41"],
  frame42: ["frame42"],
  frame43: ["frame43"],
  frame44: ["frame44"],
  frame70: ["frame70"],
  rectangle28: ["rectangle28"],
  search5: ["search5"],
  plus: ["plus"],
  plus2: ["plus2"],
  plus3: ["plus3"],
  rectangle31: ["rectangle31"],
  search6: ["search6"],
  noEntry: ["noEntry"],
  noEntry2: ["noEntry2"],
  cursor2: ["cursor2"],
  xyConceptNbg1: ["xyConceptNbg1"],
  rectangle65: ["rectangle65"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicProjectspage__ArgProps,
          internalVariantPropNames: PlasmicProjectspage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicProjectspage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProjectspage";
  } else {
    func.displayName = `PlasmicProjectspage.${nodeName}`;
  }
  return func;
}

export const PlasmicProjectspage = Object.assign(
  // Top-level PlasmicProjectspage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    desktop4: makeNodeComponent("desktop4"),
    rectangle15: makeNodeComponent("rectangle15"),
    fullToolStorageBox: makeNodeComponent("fullToolStorageBox"),
    project: makeNodeComponent("project"),
    cost: makeNodeComponent("cost"),
    speed: makeNodeComponent("speed"),
    user: makeNodeComponent("user"),
    projectName: makeNodeComponent("projectName"),
    projectName2: makeNodeComponent("projectName2"),
    projectName3: makeNodeComponent("projectName3"),
    projectName4: makeNodeComponent("projectName4"),
    rectangle25: makeNodeComponent("rectangle25"),
    rectangle26: makeNodeComponent("rectangle26"),
    rectangle27: makeNodeComponent("rectangle27"),
    p00122: makeNodeComponent("p00122"),
    completed: makeNodeComponent("completed"),
    onGoing: makeNodeComponent("onGoing"),
    started: makeNodeComponent("started"),
    late: makeNodeComponent("late"),
    p001222: makeNodeComponent("p001222"),
    p001223: makeNodeComponent("p001223"),
    p001224: makeNodeComponent("p001224"),
    lessThan: makeNodeComponent("lessThan"),
    moreThan: makeNodeComponent("moreThan"),
    rectangle23: makeNodeComponent("rectangle23"),
    search: makeNodeComponent("search"),
    rectangle24: makeNodeComponent("rectangle24"),
    search2: makeNodeComponent("search2"),
    rectangle29: makeNodeComponent("rectangle29"),
    search3: makeNodeComponent("search3"),
    rectangle30: makeNodeComponent("rectangle30"),
    search4: makeNodeComponent("search4"),
    desktop5: makeNodeComponent("desktop5"),
    rectangle16: makeNodeComponent("rectangle16"),
    fullToolStorageBox2: makeNodeComponent("fullToolStorageBox2"),
    project2: makeNodeComponent("project2"),
    cost2: makeNodeComponent("cost2"),
    speed2: makeNodeComponent("speed2"),
    user2: makeNodeComponent("user2"),
    logout: makeNodeComponent("logout"),
    frame36: makeNodeComponent("frame36"),
    frame39: makeNodeComponent("frame39"),
    frame38: makeNodeComponent("frame38"),
    frame37: makeNodeComponent("frame37"),
    frame40: makeNodeComponent("frame40"),
    frame65: makeNodeComponent("frame65"),
    responsable: makeNodeComponent("responsable"),
    frame66: makeNodeComponent("frame66"),
    frame67: makeNodeComponent("frame67"),
    frame68: makeNodeComponent("frame68"),
    frame69: makeNodeComponent("frame69"),
    frame55: makeNodeComponent("frame55"),
    frame56: makeNodeComponent("frame56"),
    frame57: makeNodeComponent("frame57"),
    frame58: makeNodeComponent("frame58"),
    frame59: makeNodeComponent("frame59"),
    frame50: makeNodeComponent("frame50"),
    frame51: makeNodeComponent("frame51"),
    frame52: makeNodeComponent("frame52"),
    frame53: makeNodeComponent("frame53"),
    frame54: makeNodeComponent("frame54"),
    frame45: makeNodeComponent("frame45"),
    frame46: makeNodeComponent("frame46"),
    frame47: makeNodeComponent("frame47"),
    frame48: makeNodeComponent("frame48"),
    frame49: makeNodeComponent("frame49"),
    frame60: makeNodeComponent("frame60"),
    frame61: makeNodeComponent("frame61"),
    frame62: makeNodeComponent("frame62"),
    frame63: makeNodeComponent("frame63"),
    frame64: makeNodeComponent("frame64"),
    frame41: makeNodeComponent("frame41"),
    frame42: makeNodeComponent("frame42"),
    frame43: makeNodeComponent("frame43"),
    frame44: makeNodeComponent("frame44"),
    frame70: makeNodeComponent("frame70"),
    rectangle28: makeNodeComponent("rectangle28"),
    search5: makeNodeComponent("search5"),
    plus: makeNodeComponent("plus"),
    plus2: makeNodeComponent("plus2"),
    plus3: makeNodeComponent("plus3"),
    rectangle31: makeNodeComponent("rectangle31"),
    search6: makeNodeComponent("search6"),
    noEntry: makeNodeComponent("noEntry"),
    noEntry2: makeNodeComponent("noEntry2"),
    cursor2: makeNodeComponent("cursor2"),
    xyConceptNbg1: makeNodeComponent("xyConceptNbg1"),
    rectangle65: makeNodeComponent("rectangle65"),
    // Metadata about props expected for PlasmicProjectspage
    internalVariantProps: PlasmicProjectspage__VariantProps,
    internalArgProps: PlasmicProjectspage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicProjectspage;
/* prettier-ignore-end */
